In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
orig_img = cv2.imread("C:/Users/user/Desktop/Gunti.jpg")

In [3]:
orig_img.shape

(3456, 4608, 3)

In [4]:
img = orig_img.reshape(-1,3)

In [5]:
img.shape

(15925248, 3)

In [6]:
img = np.float32(img)

In [8]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)

In [25]:
k = 5

In [26]:
attempts = 3

In [27]:
ret,label,center=cv2.kmeans(img,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)

In [28]:
center = np.uint8(center)

In [29]:
ret

14280523058.891708

In [30]:
label

array([[0],
       [0],
       [0],
       ...,
       [2],
       [2],
       [2]], dtype=int32)

In [31]:
label.shape

(15925248, 1)

In [32]:
center.shape

(5, 3)

In [33]:
center

array([[110, 122, 127],
       [231, 239, 236],
       [ 71,  75,  75],
       [ 86, 110, 234],
       [ 34,  35,  34]], dtype=uint8)

In [34]:
img

array([[115., 112., 108.],
       [114., 111., 107.],
       [113., 112., 108.],
       ...,
       [ 67.,  67.,  73.],
       [ 60.,  60.,  66.],
       [ 60.,  60.,  66.]], dtype=float32)

In [35]:
res = center[label.flatten()]

In [36]:
res2 = res.reshape((orig_img.shape))

In [37]:
cv2.imwrite('segmented.jpg',res2)

True